// src/services/assignment.service.js
const prisma = require("../config/prisma");

/**
 * NOTE ON RELATION NAMES
 * The schema (generated by `prisma db pull`) names the relations
 * `Course`, `User` and `AssignmentSubmission` — not `course` / `mentor` /
 * `submissions`. Querying the lowercase names throws a Prisma validation
 * error, which is what produced the 500 on GET /api/assignments.
 * We query the real names and re-map them to friendly keys for the frontend.
 */

const shape = (a) => {
  if (!a) return a;
  const { Course, User, AssignmentSubmission, ...rest } = a;
  return {
    ...rest,
    course: Course || null,
    mentor: User || null,
    submissions: AssignmentSubmission || [],
  };
};

class AssignmentService {
  async create(data, mentorId) {
    if (!data.title || !String(data.title).trim()) {
      const e = new Error("Assignment title is required."); e.statusCode = 400; throw e;
    }
    if (!data.courseId) {
      const e = new Error("Course is required."); e.statusCode = 400; throw e;
    }
    if (!data.dueDate) {
      const e = new Error("Due date is required."); e.statusCode = 400; throw e;
    }

    const marks = Number(data.totalMarks);
    if (!Number.isFinite(marks) || marks <= 0) {
      const e = new Error("Total marks must be greater than 0."); e.statusCode = 400; throw e;
    }

    const course = await prisma.course.findUnique({
      where: { id: Number(data.courseId) },
      select: { id: true },
    });
    if (!course) {
      const e = new Error("Course not found."); e.statusCode = 404; throw e;
    }

    const created = await prisma.assignment.create({
      data: {
        title: String(data.title).trim(),
        description: data.description || "",
        dueDate: new Date(data.dueDate),
        totalMarks: marks,
        courseId: Number(data.courseId),
        mentorId: Number(mentorId),
        // `updatedAt` has no @default / @updatedAt in the schema, so it must
        // be supplied explicitly or the insert fails.
        updatedAt: new Date(),
      },
      include: { Course: true },
    });

    return shape(created);
  }

  async getAll() {
    const rows = await prisma.assignment.findMany({
      include: {
        Course: { select: { id: true, title: true } },
        User: { select: { id: true, name: true, email: true } },
        AssignmentSubmission: { select: { id: true } },
      },
      orderBy: { createdAt: "desc" },
    });
    return rows.map(shape);
  }

  async getById(id) {
    const row = await prisma.assignment.findUnique({
      where: { id: Number(id) },
      include: {
        Course: { select: { id: true, title: true } },
        User: { select: { id: true, name: true, email: true } },
        AssignmentSubmission: {
          include: { User: { select: { id: true, name: true, email: true } } },
          orderBy: { submittedAt: "desc" },
        },
      },
    });

    if (!row) {
      const e = new Error("Assignment not found."); e.statusCode = 404; throw e;
    }
    return shape(row);
  }

  async update(id, data) {
    const existing = await prisma.assignment.findUnique({
      where: { id: Number(id) },
      select: { id: true },
    });
    if (!existing) {
      const e = new Error("Assignment not found."); e.statusCode = 404; throw e;
    }

    // Whitelist the fields so stray body keys (course, submissions, mentor…)
    // can't reach Prisma and blow up the update.
    const payload = { updatedAt: new Date() };
    if (data.title !== undefined) payload.title = String(data.title).trim();
    if (data.description !== undefined) payload.description = data.description || "";
    if (data.dueDate !== undefined) payload.dueDate = new Date(data.dueDate);
    if (data.totalMarks !== undefined) {
      const m = Number(data.totalMarks);
      if (!Number.isFinite(m) || m <= 0) {
        const e = new Error("Total marks must be greater than 0."); e.statusCode = 400; throw e;
      }
      payload.totalMarks = m;
    }
    if (data.courseId !== undefined) payload.courseId = Number(data.courseId);

    const updated = await prisma.assignment.update({
      where: { id: Number(id) },
      data: payload,
      include: { Course: { select: { id: true, title: true } } },
    });

    return shape(updated);
  }

  async delete(id) {
    const existing = await prisma.assignment.findUnique({
      where: { id: Number(id) },
      select: { id: true },
    });
    if (!existing) {
      const e = new Error("Assignment not found."); e.statusCode = 404; throw e;
    }

    // Submissions have no cascade rule, so remove them first inside one
    // transaction — otherwise deleting a submitted assignment fails.
    await prisma.$transaction([
      prisma.assignmentSubmission.deleteMany({ where: { assignmentId: Number(id) } }),
      prisma.assignment.delete({ where: { id: Number(id) } }),
    ]);

    return { success: true, message: "Assignment deleted successfully." };
  }

  async submitAssignment(assignmentId, studentId, data) {
    const assignment = await prisma.assignment.findUnique({
      where: { id: Number(assignmentId) },
      select: { id: true },
    });
    if (!assignment) {
      const e = new Error("Assignment not found."); e.statusCode = 404; throw e;
    }

    const already = await prisma.assignmentSubmission.findFirst({
      where: { assignmentId: Number(assignmentId), studentId: Number(studentId) },
      select: { id: true },
    });
    if (already) {
      const e = new Error("You have already submitted this assignment.");
      e.statusCode = 409; throw e;
    }

    return await prisma.assignmentSubmission.create({
      data: {
        assignmentId: Number(assignmentId),
        studentId: Number(studentId),
        submissionText: data.submissionText || null,
        attachment: data.attachment || null,
      },
    });
  }

  async getSubmissions(id) {
    const rows = await prisma.assignmentSubmission.findMany({
      where: { assignmentId: Number(id) },
      include: { User: { select: { id: true, name: true, email: true } } },
      orderBy: { submittedAt: "desc" },
    });

    return rows.map(({ User, ...rest }) => ({ ...rest, student: User || null }));
  }
}

module.exports = new AssignmentService();